config/routes.rb
MelezhaBy::Application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :companies

  get 'list' => 'list#list'

  devise_for :users

  get 'search' => 'search#index'

  root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)

    if user.role? :admin
      can :manage, :all
    else
      can [:index, :new, :create], :all
      can [:show, :edit, :update, :destroy ], Company do |company|
        company.try(:user) == user
      end
    end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :company
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :addresses
  has_many :contacts
  has_many :services
  belongs_to :user

  has_attached_file :logo, :styles => { :medium => "500x300>" }
  validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
 
  before_validation :clear_logo

  def delete_logo=(value)
    @delete_logo = !value.to_i.zero?
  end
  
  def delete_logo
    !!@delete_logo
  end
  alias_method :delete_logo?, :delete_logo

def clear_logo
  self.logo = nil if delete_logo? && !logo.dirty?
end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :company
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/service.rb
class Service < ActiveRecord::Base
	belongs_to :company
end

app/models/tip.rb
class Tip < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :companies
  has_and_belongs_to_many :roles

  def role?(role)
      return !!self.roles.find_by_name(role.to_s.camelize)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery

  before_filter :update_sanitized_params, if: :devise_controller?

  #attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :confirmed_at

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_in) {|u| u.permit( :email, :password, :remember_me )}
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit( :email, :password, :password_confirmation )}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit( :email, :password, :password_confirmation, :current_password )}
  end

  def company_params
    params.require(:company).permit!
  end

  before_filter do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_filter :authenticate_user!
  load_and_authorize_resource
  check_authorization

  # GET /companies
  # GET /companies.json
  def index
    user = User.find(current_user)
    @companies = user.companies

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])
    @company.user_id = current_user.id

    respond_to do |format|
      if @company.save
        format.html { redirect_to companies_url, notice: t('company_added') }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])
    # if params[:logo[rm_logo]] == true
    # end

    respond_to do |format|
      if @company.update_attributes(params[:company])
        @company.touch
        format.html { redirect_to companies_url, notice: t('company_updated') }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :ok }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  	if params['q'] != "" and params['q'] != nil
  		# query = params['search-keywords'].split(/'([^']+)'|"([^"]+)"|\s+|\+/).reject{|x| x.empty?}.map{|x| x.inspect }*' && '
  		query = params['q']
  		@companies = Company.search query, :star => true, :match_mode => :extended
		# @companies = @search.results

  	end
  	  	
  	@companies_last = Company.limit(8).order('id desc')

  end

end

app/controllers/list_controller.rb
class ListController < ApplicationController
	
	def list
		@companies_all = Company.order('id desc').all
		@companies_total = Company.last
	end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index

  	if params['search-keywords']
  		@search = Company.search do
		    fulltext params['search-keywords']
		  end
		  @companies = @search.results
  	end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def tips
		Tip.order("RAND()").limit(1).first
	end
	# @companies_total = Company.last
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
	@companies_total = Company.last
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/search_helper.rb
module SearchHelper
	@companies_total = Company.last
end

app/views/companies/_form.html.erb
<%= form_for(@company, :html => { :multipart => true } ) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>

  <% end %>

    <div class="clearfix">
      <%= f.label :title, "Название компании" %>
      <div class="input"><%= f.text_field :title, :class => "xxlarge", :placeholder => "например: ООО \"Моя компания\"" %></div>
    </div>

    <%- unless @company.new_record? || !@company.logo? -%>
      <div class="clearfix">          
        <div class="logo_for_edit">
          <%= image_tag(@company.logo.url(:medium), :alt => 'Logo', :title => 'Логотип') %><br />
        </div>
          <%= f.label(:delete_logo, 'Удалить логотип') %>
          <div class="input"><%= f.check_box(:delete_logo) %></div>
      </div>
    <%- end -%>

    <div class="clearfix">
      <label for="fileInput">Логотип компании</label>
      <div class="input">
        <%= f.file_field :logo, :class => "input-file", :id =>"fileInput" %>
      </div>
    </div>

    <div class="clearfix">
      <%= f.label :overview, "Описание" %>
      <div class="input"><%= f.text_area :overview, :class => "xxlarge", :placeholder => "например: вывоз мусора, уборка офисов, инвестиции" %></div>
    </div>

    <div class="clearfix">
      <%= f.label :addr, "Адрес" %>
      <div class="input"><%= f.text_area :addr, :class => "xxlarge",  :rows => "3", :placeholder => "например: Мележа 1-1001" %></div>
    </div>

    <div class="clearfix">
      <%= f.label :tel, "Телефон" %>
      <div class="input">
        <%= f.phone_field :tel, :class => "xxlarge", :placeholder => "например: +375 17 123-45-67, (017) 123-45-67", :title => "Номер(а) телефона(ов)" %>
      </div>
    </div>

    <div class="clearfix">
      <%= f.label :fax, "Факс" %>
      <div class="input">
        <%= f.phone_field :fax, :class => "xxlarge", :placeholder => "например: +375 17 123-45-67, (017) 123-45-67", :title => "Номер(а) факса(ов)" %>
      </div>
    </div>

    <div class="clearfix">
      <%= f.label :email, "Электронная почта" %>
      <div class="input">
        <%= f.email_field :email, :class => "xxlarge", :placeholder => "например: info@melezha.by", :title => "Адрес электронной почты для связи. Виден всем." %>
      </div>
    </div>

    <div class="clearfix">
      <%= f.label :site, "Сайт" %>
      <% @company.site? ? val=@company.site : val="http://" %>
      <div class="input">
        <%= f.url_field :site, :class => "xxlarge", :placeholder => "например: http://melezha.by", :title => "Адрес сайта должен начинаться с http:// или https://" %>
      </div>
    </div>

    <div class="clearfix">
      <%= f.label :skype, "Skype" %>
      <div class="input"><%= f.text_field :skype, :class => "xxlarge", :placeholder => "например: echo123", :title => "Skype" %></div>
    </div>

    <div class="clearfix">
      <%= f.label :icq, "ICQ" %>
      <div class="input"><%= f.text_field :icq, :class => "xxlarge", :placeholder => "например: 123-456-789 или 123456789", :title => "Номер ICQ" %></div>
    </div>

  <div class="clearfix">
    <div class="input">
      <%= f.submit "Отправить", :class => "btn success" %>
      <%= link_to 'Отмена', companies_path, :class => "btn" %>
    </div>
  </div>

<% end %>

app/views/companies/edit.html.erb
<div class="span14">
  <h1>Редактирование компании</h1>

  <%= render 'form' %>
</div>

app/views/companies/index.html.erb
<div class="span14">
  <h1>Ваши компании</h1>

  <table class="">
  <tr>
      <th class="span12"></th>
      <th>Обновлено</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
  </tr>
  <% @companies.each do |company| %>
  <tr>
      <td class="span12">
        <strong><%= company.title %></strong><br />
        <% if company.logo? %><%= image_tag company.logo(:medium) %><% end %>
        <%= simple_format(company.overview) %>
      </td>
      <td>
        <% if company.updated_at < Date.today-30 %>
          <font color="red"><%= company.updated_at.strftime '%d.%m.%Y' %></font>
        <% else %>
          <%= company.updated_at.strftime '%d.%m.%Y' %>
        <% end %>
      </td>
      <td><%= link_to 'Редактировать', edit_company_path(company), :class => "btn primary" %></td>
      <td><%= link_to 'Удалить', company, confirm: 'Вы уверены?', method: :delete, :class => "btn danger" %></td>
  </tr>
  <% end %>
  </table>
  <br />

  <div align="right"><%= link_to 'Добавить компанию', new_company_path, :class => "btn success" %></div>
</div>

app/views/companies/new.html.erb
<div class="span14">
	<h1>Добавление компании</h1>

	<%= render 'form' %>

</div>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/home/index.html.erb
<div class="span14">

  <% unless @companies.present? %>

    <% if params['q'].present? %>
    К сожалению ничего не найдено. Если это ваш бизнес, то вы можете <%= link_to "добавить вашу Компанию", companies_path %>.
    <% end %>

    <div class="row">
      <div class="span6">
        <div class="list-top-query" id="list-top-query">
          <h5>Примеры запросов:</h5>
          <ul>
            <li><a href='/?q=Кафе+%7C+Ресторан+%7C+Кулинария+%7C+"Продукты питания"'>Где покушать?</a>, <a href="/?q=Продукты+питания">Где купить продукты?</a></li>
            <li><a href="/?q=офисная+бумага">Офисная бумага</a></li>
            <li><a href='/?q="Подключение+к+сети+Интернет"+%7C+Провайдер'>Подключение к сети Интернет</a></li>
            <li><a href="/?q=Заправка+картриджей">Заправка картриджей</a></li>
            <li><a href="/?q=Бухгалтерия">Бухгалтерские услуги</a></li>
            <li><a href="/?q=Аптека">Аптека</a></li>
            <li><a href="/?q=Компьютеры">Компьютеры</a></li>
            <li><a href="/?q=Разработка+сайтов">Разработка сайтов</a>, <a href="/?q=Продвижение+сайтов">Продвижение сайтов</a></li>
            <li>
              <a href="/?q=сниму+%7C+снять+офис">сниму офис</a>,
              <a href="/?q=сдам%7C+сдается+офис">сдам офис</a>, 
              <a href="/?q=куплю+офис">куплю офис</a>, 
              <a href="/?q=продам+офис">продам офис</a>
            </li>
          </ul>
        </div>
      </div>

      <div class="span6">
        <div class="list-top-query" id="list-top-query">
          <h5>Новые Компании:</h5>
          <ul>
            <% @companies_last.each do |company_last| %>
              <li><a href="/?q=<%=h company_last.title %>" title='<%= strip_tags(company_last.overview) %>'><%= company_last.title %></a><br></li>
            <% end %>
            <li><strong><%= link_to "Все Компании >>", list_path %></strong></li>
          </ul>

        </div>
      </div>
    </div>

  <% end %>

  <% if @companies.present? %>
    <% @companies.each do |company| %>
      <h3><%= company.title %></h3>
          <% if company.logo? %><%= image_tag company.logo(:medium) %><br /><% end %>
          <%= simple_format(company.overview) %>
          <% if company.addr.present? %>Адрес: <%= company.addr %><br /><% end %>
          <% if company.tel.present? %>Телефон: <%= company.tel %><br /><% end %>
          <% if company.fax.present? %>Факс: <%= company.fax %><br /><% end %>
          <% if company.email.present? %>Электронная почта: <%= mail_to company.email, nil, :encode => "javascript" %><br /><% end %>
          <% if company.site.present? %>Сайт: <%= link_to company.site, company.site %><br /><% end %>
          <% if company.skype.present? %>Skype: <%= company.skype %><br /><% end %>
          <% if company.icq.present? %>ICQ: <%= company.icq %><% end %><br />
          <i>Информация обновлена: <%= company.updated_at.strftime '%d.%m.%Y' %></i>
      <hr>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>Мележа.by</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

    <style type="text/css">

      /* Override some defaults */
      html, body {
        background-color: #eee;
      }
      body {
        padding-top: 40px; /* 40px to make the container go all the way to the bottom of the topbar */
      }
      .container > footer p {
        text-align: center; /* center align it with the container */
      }
      .container {
        width: 820px; /* downsize our container to make the content feel a bit tighter and more cohesive. NOTE: this removes two full columns from the grid, meaning you only go to 14 columns and not 16. */
      }

      /* The white background content wrapper */
      .content {
        background-color: #fff;
        padding: 20px;
        margin: 0 -20px; /* negative indent the amount of the padding to maintain the grid system */
        -webkit-border-radius: 0 0 6px 6px;
           -moz-border-radius: 0 0 6px 6px;
                border-radius: 0 0 6px 6px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
                box-shadow: 0 1px 2px rgba(0,0,0,.15);
      }

      /* Page header tweaks */
      .page-header {
        background-color: #f5f5f5;
        padding: 20px 20px 10px;
        margin: -20px -20px 20px;
      }

      /* Styles you shouldn't keep as they are for displaying this base example only
      .content .span10,
      .content .span4 {
        min-height: 500px;
      } */
      /* Give a quick and non-cross-browser friendly divider */
      .content .span4 {
        margin-left: 0;
        padding-left: 19px;
        border-left: 1px solid #eee;
      }

      .topbar .btn {
        border: 0;
      }
    </style>
    
</head>
<body>

  <div class="container">
    <div class="content">

      <%- if controller_name == 'home' %>
          <div class="page-header" align="center">
              <fieldset>
                <legend align="center">Поиск услуг, товаров и Компаний на улице Мележа и в округе</legend>
                <div class="clearfix">
                  <form id="main-search-form" action=<%= url_for root_path %> method="GET">
                    <div class="input">
                      <% params['q'].present? ? value=params['q'] : value="" %>
                      <input class="xxlarge span11 main-input-search" id="xlInput" name="q" size="100" type="text" placeholder="Например: офисная бумага" value="<%= value %>" >
                      <button class="btn primary large">Найти</button>
                    </div>
                  </form>
                </div>
              </fieldset>
                    <%- if !tips.nil? %>
                      <%= tips.tip_text %>
                    <% end %>
          </div>
      <% end -%>

      <div class="row">

          <% if notice %>
            <div class="span14" align="center">
              <div class="alert-message success fade in" data-alert="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <%= notice %>
              </div>
            </div>
          <% end %>

          <% if alert %>
            <div class="span14" align="center">
              <div class="alert-message warning fade in" data-alert="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <%= alert %>
              </div>
            </div>
          <% end %>

        <%= yield %>

      </div>

    </div>

    <footer>
    <div class="row">
      <div class="span6">
        Сделано с помощью: <a href="http://rubyonrails.org/">Ruby on Rails</a>, <a href="http://twitter.github.com/bootstrap/">Bootstrap</a>
      </div>
      <div class="span1" align="center">
        <a href="http://www.twitter.com/MelezhaBY"><img src="http://twitter-badges.s3.amazonaws.com/twitter-b.png" alt="Читать MelezhaBY в Твиттере"/></a>
      </div>
      <div class="span6" align="right">
        Контакт: <%= mail_to "melezha@melezha.by", "melezha@melezha.by", :encode => "javascript" %>
      </div>
    </div>
    <div class="row">
      <div class="span14">
<!--         Интернет: <a href="/?q=ТЕЛЕКОМ+МЕДИА+СИСТЕМС"><img src="http://torrents.by/forum/images/tcm.gif"></a> -->
      </div>
    </div>
    </footer>

  </div>

  <!-- Top menu START -->
  <div class="topbar-wrapper" style="z-index: 5;">
      <div class="topbar" data-dropdown="dropdown">
        <div class="topbar-inner">
          <div class="container">
            <h3><a href=<%= root_path %>>
                  Мележа.by
<!--                   <sup><font color="red" style="font-weight: bold;">
                    Продается!
                    </font></sup> -->
                </a>
            </h3>
            <ul class="nav">
              <% if user_signed_in? %>
                <li><a href=<%= companies_path %>>Ваши Компании</a></li>
              <% else %>
                <li><a href=<%= companies_path %>>Добавить Компанию</a></li>
              <% end %>
            </ul>
            <ul class="nav secondary-nav">            
                  <% if user_signed_in? %>
                    <li><%= link_to "Профиль", edit_user_registration_path %></li>
                    <li><%= link_to "Выход", destroy_user_session_path, :method => 'delete' %></li>
                  <% else %>
                    <li><a href=<%= new_user_session_path %>>Вход</a></li>
                    <li><a href=<%= new_user_registration_path %>>Регистрация</a></li>
                  <% end %>
            </ul>
          </div>
        </div><!-- /topbar-inner -->
      </div><!-- /topbar -->
  </div>    
  <!-- Top menu END -->


<script type="text/javascript">
reformal_wdg_domain    = "melezhaby";
reformal_wdg_mode    = 0;
reformal_wdg_title   = "Мележа.by";
reformal_wdg_ltitle  = "Оставьте свой отзыв";
reformal_wdg_lfont   = "";
reformal_wdg_lsize   = "";
reformal_wdg_color   = "#FFA000";
reformal_wdg_bcolor  = "#516683";
reformal_wdg_tcolor  = "#FFFFFF";
reformal_wdg_align   = "right";
reformal_wdg_charset = "utf-8";
reformal_wdg_waction = 0;
reformal_wdg_vcolor  = "#9FCE54";
reformal_wdg_cmline  = "#E0E0E0";
reformal_wdg_glcolor  = "#105895";
reformal_wdg_tbcolor  = "#FFFFFF";
 
reformal_wdg_bimage = "7688f5685f7701e97daa5497d3d9c745.png";
 
</script>

<script type="text/javascript" language="JavaScript" src="http://reformal.ru/tab6.js?charset=utf-8"></script><noscript><a href="http://melezhaby.reformal.ru">Мележа.by feedback </a> <a href="http://reformal.ru"><img 
src="http://reformal.ru/i/logo.gif" /></a></noscript>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter19340209 = new Ya.Metrika({id:19340209,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/19340209" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

</body>
</html>

app/views/list/list.html.erb
<div class="span14">
		<table class="zebra-striped condensed-table">
		<tbody>
		<% @companies_all.each do |company| %>
			<tr>
	       		<td><a href="/?q=<%= html_escape(company.title) %>"><%= company.title %></a></td>
	       		<td title="<%= strip_tags(company.overview) %>"><%= strip_tags(truncate(company.overview, :length => 75)) %></td>
	       	</tr>
	    <% end %>
	    </tbody>
	    </table>
    <strong>Всего Компаний:</strong> <%= @companies_total.id %>
</div>